# Generated by Django 2.2.1 on 2019-07-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='Jenis',
            new_name='jenis',
        ),
        migrations.AlterField(
            model_name='barang',
            name='bukti',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
