# Generated by Django 2.2.1 on 2019-07-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20190704_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='bukti',
            new_name='bukti_diterima',
        ),
    ]
