# Generated by Django 2.2.1 on 2019-07-04 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190704_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='nama',
            new_name='nama_barang',
        ),
    ]
