# Generated by Django 2.2.1 on 2019-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20190704_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(max_length=1),
        ),
    ]
