# Generated by Django 2.2.1 on 2019-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190704_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
