# Generated by Django 2.2.1 on 2019-07-04 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20190704_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='barang',
            name='jumlah',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='keterangan',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='barang',
            name='nama_barang',
            field=models.CharField(max_length=50),
        ),
    ]
