# Generated by Django 2.2.1 on 2019-07-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20190704_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barang',
            name='jenis',
            field=models.CharField(choices=[('masuk', 'Masuk'), ('keluar', 'Keluar')], max_length=6),
        ),
    ]
