# Generated by Django 2.2.3 on 2019-07-16 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20190707_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='keluar',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='masuk',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='barang',
            name='total',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
